language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: Ijco3Ndqms59O1K1KJPhkKuNdd5MDN8Ghub/Y+0jL0Luc8ASfw+cV7UU/Dx09igvOqj6yfsuo318MIOm1gH78uMy5if+RJUhfA4wkxkJn00KnUZedw156oj0aGb6k0mYpgKsJHuwfl5sfVlXe9iXIeuibpSxopn1dBzLe6c8ZxW9nulnGJYGoo68Kq/nAVvpQYOdmgZ3RlYmKLojZSW3A15GXIvSk1glokOKULFMJh0+TGN/odzRSh1F57fmZpUTEqUSwEbVuoy755bqlsd+jVL0XnMZg16ZvNcKyGQMLngDgMtwo9xR6Zj0ijCfwzfFQFHCZUy8b10jaIC6sPq4exwr+wcUAximLMf+CKbSyvFZdU4Wk/LiHnCjBrGnjLj6vhpF7tG1iKW8LAgAFCLENnbpQ/UeuTPpYpXzaHJsyNd/Wg9864ZeJ9UlXAG4LS2QJPWmvOx54WZxVWQ/Kw+U38HZgKP+iOmaIRmcuH4iDodUYT8L6Kq8QUhfEIBoP7aeY3Q6rqY5mW+8wbmUmdZfsN4JYRhKnBq8r8GjHAh67xlGm+LlmNAcpKK0VvI7LnJP5YLYqZwDv1GeOYNCQQwVc5ZL80nqCXa9/pyMa87A3vHlHd/wIC9KDrpszv/Wdt3soMe1D4YsSYWTDZdQJraVisROcaZT7WSXGLHNMDQGlJU=
  on:
    branches: true
