language: node_js
node_js:
- '5'

deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: b1yXD4PS/ylgusigeF+2YBOWdSJiAn1g99hHql8stI+9qyzvDhl6d47i7xUV6GZ9zxp1nytz14IHyKMzFfs5FIcoaVFKqmLhgeCc63r7bE2OxiEuzT9VAkpGCs907rrKG05GZ8QEcziwQrb9LZrPHqE8OtkqzB8+fyoCx3gJ6zYNOjk8bKdg9WPaAtO/cXHfXp4Mk4npg4ADouQxttXrJJB/tYD1ovFnQ0LehKN7aiEZLhGX4fXRWAQfEXvyk6EhLA3b6aqW9yQWXxMXR4n1gncyyf/tidWEXA0lJi9r5CBzk5frzAR20M37PzWZGCbfBjQfRFKLcYeL9pWiWiN7oEMIv7E/xj5QifFQ804hBvtjRu7S3xHVz1l8A8es4F8QD55R1zYMv7zUtTmSY8EXnjIJ6ohHmclvCOKFTg/5DnD5Nf+dZralOoNk0iYxs2DaqEnWb29NViCErlqrPJtd/XWlmxR+NNzuOvBRj0hTNr8L8/ZFbfy8M7LkpT2j7S5qm6gGuUPy01/nhDt7mqZEXT/WbVujVOkMB1GQZdfPW1YHNUkTBsfO6f2bTZrukZAVOHYHR7CeSLcKETAbKlUeRL3TUEJnNwQ84FUBkcH/aRK5kczJ8xhtFcUj2AhXb5poRT8nzGF0og3R5/WBcZSHrqZorEgl/zzQPOTl33jmD9g=
  on:
    tags: true
